# Generated by Django 6.1.1 on 2026-09-23 18:17

from django.contrib.auth.hashers import make_password
from django.db import migrations

def create_initial_account(apps, schema_editor):
    Account = apps.get_model("accounts", "Account")
    AccountInfo = apps.get_model("accounts", "AccountInfo")

    email = "cid@workboard.local"

    if AccountInfo.objects.filter(email=email).exists():
        return

    account = Account.objects.create(
        username="elcid",
        password=make_password("Cid123!"),
    )

    AccountInfo.objects.create(
        account=account,
        email=email,
        name="Rodrigo",
        last_name="Díaz de Vivar",
        role="member",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_initial_account,
            migrations.RunPython.noop,
        ),
    ]